### ISSUE TITLE
[Enhancement] Show only the small icon in mobile view

### ISSUE THREAD

**Issue by iamdarkle** [justoverclockl/flarum-ext-feedback#4]
It's not a priority and can be fixed with CSS by hiding the `<span>Feedback</span>` but maybe it would be nice to have it by default in the extension for those who don't know how to do it with CSS, to take less screen space in the mobile version.

**Comment by justoverclockl** [comment]
yes i could definitely work on this :)

**Comment by justoverclockl** [comment]
included in 0.1.5
